name: RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

      - name: Download PRIVATE repository
        uses: actions/checkout@v4
        with:
          repository: drisrida123455-wq/RDP-SEC-001-WIN-11
          token: ${{ secrets.PAT }}
          path: private-source
          fetch-depth: 1
          show-progress: false

      - name: Download PRIVATE installer
        uses: actions/checkout@v4
        with:
          repository: drisrida123455-wq/RDP-SEC-001-INSTALLER-WIN-11
          token: ${{ secrets.PAT }}
          path: private-installer
          fetch-depth: 1
          show-progress: false

      - name: Run PRIVATE code HERE
        shell: pwsh
        env:
          USER_RDP: ${{ secrets.USER_RDP }}
          PASS_RDP: ${{ secrets.PASS_RDP }}
          SUPERDMZ_TOKEN: ${{ secrets.SUPERDMZ_TOKEN }}
        run: |
          $ErrorActionPreference = "Stop"

          $script = Join-Path `
            $env:GITHUB_WORKSPACE `
            "private-source\rdp.ps1"

          if (-not (Test-Path $script)) {
              throw "rdp.ps1 not found in PRIVATE repository."
          }

          Write-Host "=========================================="
          Write-Host " RDP RUNNER"
          Write-Host "=========================================="
          Write-Host "Repository: PUBLIC"
          Write-Host "Runner: $env:RUNNER_NAME"
          Write-Host "=========================================="

          & pwsh `
            -NoLogo `
            -NoProfile `
            -NonInteractive `
            -ExecutionPolicy Bypass `
            -File $script

          if ($LASTEXITCODE -ne 0) {
              throw "Private code failed. ExitCode=$LASTEXITCODE"
          }
